### ISSUE TITLE
Missing line on Constant Motion?

### ISSUE THREAD

**Issue by r0bd0g** [rjkiv/rb3_plus#6]
I'm confused why none of the harmony upgrades I've seen feature the line "random thoughts of neat disorder" in measure 132? It's there on solo, but never on harmonies.

**Comment by rjkiv** [comment]
fixed, nice catch

**Comment by r0bd0g** [comment]
While I have a thread I want to pass along a couple things:
- The harmony upgrade for "What's Your Favorite Dinosaur?" appears to have gotten lost in the ether. This repo doesn't seem to have RBN harmonies in it, but RBHP has forgotten that they have it; it's never been brought forward to the main repo. Their main repo doesn't let me open issues so I'm counting on your to pass it along.
- The harmony upgrade for "Stop & Stare" is not available anywhere. It's in RB4 but I have no idea where it came from.

**Comment by rjkiv** [comment]
I do have the upgrades for stop and stare, I can add them in a bit.

As for RBN harmonies, those will come at a later date, mainly because for the moment I want to focus on upgrading "official" HMX RB DLC. Whenever I do get to RBN harmonies, I will either vet RBHP's existing ones or chart my own as I desire - keep in mind I am only one single person, and there is only so much RBN content that one person can work on.

**Comment by r0bd0g** [comment]
Yeah I'm just trying to make people aware that the upgrade exists on that RBN song. It's hidden on a sub branch of espher's repo and nowhere else.
